### PR TITLE
add cmake target and config export for parmmg to support find package

### LINKED ISSUE #1: Add CMake Target and Config Export for ParMmg to Support find_package
see https://github.com/MmgTools/ParMmg/issues/136 for more details

### LINKED ISSUE #136: Add CMake Target and Config Export for ParMmg to Support find_package
This issue proposes adding a proper CMake export configuration for ParMmg, allowing it to be found and imported into other CMake projects using find_package. By creating an INTERFACE library target and installing necessary CMake config files, this change enables downstream projects to easily link to ParMmg without manually configuring paths.

## Changes proposed

- New Interface Target ParMmg: Defines ParMmg as an INTERFACE library, with conditional linking to either the static or shared library based on build type.
- Namespace Alias ParMmg::ParMmg: Creates a ParMmg::ParMmg namespaced alias for consistency with CMake’s modern target usage conventions.
- Config File Export: Adds ParMmgConfig.cmake and ParMmgConfigVersion.cmake, enabling find_package(ParMmg) for downstream projects.
- CMake Export Target File: Installs ParMmgTargets.cmake in the CMake install directory, which defines and exports the ParMmg::ParMmg target.

## Rationale

Previously, downstream projects could not use find_package(ParMmg) to locate and link against ParMmg, requiring manual setup of include and library paths. With this enhancement:

1.	Compatibility: ParMmg can now be integrated seamlessly into other CMake-based projects using find_package, aligning with best practices for C++ libraries.
2.	Ease of Use: By creating a target with the namespace `ParMmg::ParMmg`, users can simply link to `ParMmg::ParMmg` in their CMake projects without manual configuration.
3.	Standardization: Using exported targets and configuration files aligns with modern CMake standards, improving compatibility with larger builds and package managers.

This improvement will significantly enhance the usability of ParMmg for developers, making it easier to integrate into larger CMake-based codebases.

### PR DESCRIPTION
**Pull request by prudhomm**
- closes #136  
- closes feelpp/ParMmg#1

This has been tested with spack packaging of ParMmg and Feel++ [here](https://github.com/feelpp/spack.feelpp/tree/main/packages/parmmg)

### CODE REVIEW

**Review by Algiane — APPROVED** [review]
Thanks!

**Comment by prj-** [comment]
Please keep `develop` in sync.

**Comment by Algiane** [comment]
Thanks,
It is done but the gitlab server of Inria is off this morning so all the tests are failing (I will trigger them again this afternoon).

**Comment by prj-** [comment]
> the gitlab server of Inria is off

Color me surprised!

**Comment by prudhomm** [comment]
One of the reason i use GitHub. Downtime is very rare. I am not even sure i was ever hit by one. Not so true with the gitlab.

**Pull request merged**
