### PR TITLE
Fix CMake bis

### PR DESCRIPTION
**Pull request by prj-**
Side effect introduced by #20.

### CODE REVIEW

**Comment by Algiane** [comment]
Hi Pierre,

I have broken something in the develop branch of ParMmg: I will warn you when it will be safe to pull it.

Thanks by advance,
Algiane

**Comment by prj-** [comment]
Sorry about the mess this morning (w.r.t. #20 and #21). The error from #20 was actually reported by a FreeFEM user, but then I realized that my fix broke our Jenkins, thus #21...
Please let me know when it's safe to fetch `HEAD` of `develop`, thanks in advance.

**Comment by Algiane** [comment]
Hi Pierre,

The develop branch seems to be fixed: it is compatible with the commit 90371bef of Mmg (commit 7fa3eec is the begining of a fix for the opnbdy option but for now it may create issues with parallel input of multi-domain meshes).

Regards,
Algiane

**Comment by prj-** [comment]
Thanks, I've bumped everything in https://github.com/FreeFem/FreeFem-sources/commit/c3e4cb6a6a7fc8425ede24afc4a77eb1e9000f47. Hopefully the last update before surface adaptation is fully debugged 😄

**Pull request merged**
