### PR TITLE
Feature/clean valgrind leaks

### PR DESCRIPTION
**Pull request by Algiane**
Hello,

I have tried to fix the memory leaks raised up by @prj- in PR #48. So the test case that is run is the `libexamples/adaptation_example1` on 4 processes.

I have fixed:
  - a source and destination overlap when we creates the // input file names (commit [dd88d9](https://github.com/MmgTools/ParMmg/commit/dd88d9dd63baafd8eabb7c59fa935d3790bae961));
  - a leak in a file unit due to a missing 'close' when reading the communicators with // input file (commit [874b4e0](https://github.com/MmgTools/ParMmg/commit/874b4e0cb70873d6c3f18e582765ae9134d9d7de));
  - a memory leak due to a missing unallocation of the edge communicator after analysis (the edge communicator is the re-allocated for the computation of the edge length histogram - commit [b81904d](https://github.com/MmgTools/ParMmg/commit/b81904d674c24b58444e3472c154f0f32d84f8b7));
  - the same commit tries to patch memory leaks that occurs only when the analysis step fails.
  
  Errors that are not corrected are:
    - the `scotch` errors: those errors are in `yacc`, the tool used by scotch to parse the strategy string, I think that we can't have a correction in Mmg/ParMmg;
    - we still have an issue linked to the call to `MPI_comm_split_type()` : I don't know if it is due to something that we forget to unallocate or if it is in `MPI` and not linked to our call;
```
==14626== 880 bytes in 1 blocks are still reachable in loss record 176 of 188
==14626==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14626==    by 0x5EA7E09: opal_class_initialize (in /usr/lib/openmpi/lib/libopen-pal.so.13.0.2)
==14626==    by 0x4E69587: ??? (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==14626==    by 0x4E6A3F5: ompi_comm_nextcid (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==14626==    by 0x4E67A3E: ompi_comm_split_type (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==14626==    by 0x4E9248C: PMPI_Comm_split_type (in /usr/lib/openmpi/lib/libmpi.so.12.0.2)
==14626==    by 0x429FC1: PMMG_parmesh_SetMemGloMax (zaldy_pmmg.c:65)
==14626==    by 0x41EEF5: PMMG_Init_parameters (API_functions_pmmg.c:459)
==14626==    by 0x446384: PMMG_Init_parMesh_var_internal (variadic_pmmg.c:237)
==14626==    by 0x41C41F: PMMG_Init_parMesh (API_functions_pmmg.c:42)
==14626==    by 0x41A5EB: main (main.c:108)
``` 
  - other errors in MPI_Init that are in MPI (I think);
  
  @prj- : Please, let me know if you have any trouble with this PR.

### CODE REVIEW

**Comment by prj-** [comment]
Thanks for your time and effort.

> other errors in MPI_Init that are in MPI (I think);

I don't get this, why would errors come from the MPI implementation? I'll merge your branch in my fork and give this a test spin in PETSc (which configures MPICH with the proper flags so that it's Valgrind-clean).

**Comment by prj-** [comment]
Indeed, there are fewer leaks, thanks, but the most problematic ones (coming from MPI) are still there. There must be something still a tad off when it comes to communications or types on the communicator being passed to ParMmg.  Here is an example of a trace that I get in PETSc, which is clean otherwise.
```
==399445== 8 bytes in 1 blocks are definitely lost in loss record 1 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x958F89E: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x958FABF: MPIR_Find_local (mpir_localproc.c:50)
==399445==    by 0x94CDA1A: MPIR_Comm_create_subcomms (commutil.c:554)
==399445==    by 0x94CE3CE: MPIR_Comm_commit (commutil.c:725)
==399445==    by 0x94CEDC1: MPII_Comm_copy (commutil.c:912)
==399445==    by 0x94C16E0: MPIR_Comm_dup_with_info_impl (comm_impl.c:723)
==399445==    by 0x94C15DF: MPIR_Comm_dup_impl (comm_impl.c:699)
==399445==    by 0x92CD334: internal_Comm_dup (comm_dup.c:68)
==399445==    by 0x92CD52D: PMPI_Comm_dup (comm_dup.c:163)
==399445==    by 0x5E1CED7: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:38)
==399445==    by 0x6372ED5: DMAdaptMetric (dmgenerate.c:254)
==399445==
==399445== 8 bytes in 1 blocks are definitely lost in loss record 2 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x958F89E: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x9590056: MPIR_Find_external (mpir_localproc.c:160)
==399445==    by 0x94CDAE6: MPIR_Comm_create_subcomms (commutil.c:571)
==399445==    by 0x94CE3CE: MPIR_Comm_commit (commutil.c:725)
==399445==    by 0x94CEDC1: MPII_Comm_copy (commutil.c:912)
==399445==    by 0x94C16E0: MPIR_Comm_dup_with_info_impl (comm_impl.c:723)
==399445==    by 0x94C15DF: MPIR_Comm_dup_impl (comm_impl.c:699)
==399445==    by 0x92CD334: internal_Comm_dup (comm_dup.c:68)
==399445==    by 0x92CD52D: PMPI_Comm_dup (comm_dup.c:163)
==399445==    by 0x5E1CED7: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:38)
==399445==    by 0x6372ED5: DMAdaptMetric (dmgenerate.c:254)
==399445==
==399445== 32 bytes in 1 blocks are still reachable in loss record 3 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x964368B: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x964376A: MPIDI_VCRT_Create (mpid_vc.c:65)
==399445==    by 0x95972F8: MPIDI_CH3I_Comm_commit_pre_hook (ch3u_comm.c:190)
==399445==    by 0x94CD764: MPIR_Comm_commit_internal (commutil.c:509)
==399445==    by 0x94CE31D: MPIR_Comm_commit (commutil.c:721)
==399445==    by 0x94C9414: MPIR_init_comm_world (builtin_comms.c:33)
==399445==    by 0x952913D: MPII_Init_thread (mpir_init.c:216)
==399445==    by 0x95295E2: MPIR_Init_thread_impl (mpir_init.c:298)
==399445==    by 0x931CB7D: internal_Init_thread (init_thread.c:47)
==399445==    by 0x931CC2C: PMPI_Init_thread (init_thread.c:142)
==399445==    by 0x4C98846: PetscInitialize (pinit.c:1225)
==399445==
==399445== 360 bytes in 1 blocks are definitely lost in loss record 4 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x9477737: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x94799CE: MPIR_Csel_prune (csel.c:686)
==399445==    by 0x9476C94: MPIR_Coll_comm_init (coll_impl.c:175)
==399445==    by 0x94CE458: MPIR_Comm_commit (commutil.c:730)
==399445==    by 0x94CEDC1: MPII_Comm_copy (commutil.c:912)
==399445==    by 0x94C16E0: MPIR_Comm_dup_with_info_impl (comm_impl.c:723)
==399445==    by 0x94C15DF: MPIR_Comm_dup_impl (comm_impl.c:699)
==399445==    by 0x92CD334: internal_Comm_dup (comm_dup.c:68)
==399445==    by 0x92CD52D: PMPI_Comm_dup (comm_dup.c:163)
==399445==    by 0x5E1CED7: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:38)
==399445==    by 0x6372ED5: DMAdaptMetric (dmgenerate.c:254)
==399445==
==399445== 360 bytes in 1 blocks are definitely lost in loss record 5 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x9477737: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x94799CE: MPIR_Csel_prune (csel.c:686)
==399445==    by 0x9476C94: MPIR_Coll_comm_init (coll_impl.c:175)
==399445==    by 0x94CE4FD: MPIR_Comm_commit (commutil.c:734)
==399445==    by 0x94CEDC1: MPII_Comm_copy (commutil.c:912)
==399445==    by 0x94C16E0: MPIR_Comm_dup_with_info_impl (comm_impl.c:723)
==399445==    by 0x94C15DF: MPIR_Comm_dup_impl (comm_impl.c:699)
==399445==    by 0x92CD334: internal_Comm_dup (comm_dup.c:68)
==399445==    by 0x92CD52D: PMPI_Comm_dup (comm_dup.c:163)
==399445==    by 0x5E1CED7: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:38)
==399445==    by 0x6372ED5: DMAdaptMetric (dmgenerate.c:254)
==399445==
==399445== 360 bytes in 1 blocks are definitely lost in loss record 6 of 6
==399445==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==399445==    by 0x9477737: MPL_malloc (mpl_trmem.h:280)
==399445==    by 0x94799CE: MPIR_Csel_prune (csel.c:686)
==399445==    by 0x9476C94: MPIR_Coll_comm_init (coll_impl.c:175)
==399445==    by 0x94CE5A2: MPIR_Comm_commit (commutil.c:739)
==399445==    by 0x94CEDC1: MPII_Comm_copy (commutil.c:912)
==399445==    by 0x94C16E0: MPIR_Comm_dup_with_info_impl (comm_impl.c:723)
==399445==    by 0x94C15DF: MPIR_Comm_dup_impl (comm_impl.c:699)
==399445==    by 0x92CD334: internal_Comm_dup (comm_dup.c:68)
==399445==    by 0x92CD52D: PMPI_Comm_dup (comm_dup.c:163)
==399445==    by 0x5E1CED7: DMAdaptMetric_ParMmg_Plex (parmmgadapt.c:38)
==399445==    by 0x6372ED5: DMAdaptMetric (dmgenerate.c:254)
```

**Comment by Algiane** [comment]
Thanks for the feedback,

For me, as [parmmgadapt.c](https://gitlab.com/petsc/petsc/-/blob/main/src/dm/impls/plex/adaptors/parmmg/parmmgadapt.c) (in `PETSc`) calls `MPI_Comm_dup` (l38), it should call `MPI_Comm_free` too.
I don't know what happens with `MPI_Init_thread` but I don't think that ParMmg is responsible for that.

BR

**Comment by prj-** [comment]
We do call `MPI_Comm_free` https://gitlab.com/petsc/petsc/-/blob/d78170b0d2d686f45f2f533bbef64667586c5065/src/dm/impls/plex/adaptors/parmmg/parmmgadapt.c#L322 for the trace I sent earlier, but the communicator can't be freed because there is a hanging reference in ParMmg.
It is also why we are seeing (both in ParMmg application and in PETSc example) errors in `MPI_Init()`, since `MPI_Finalize()` doesn't do its job to the fullest extent. Again, all PETSc examples are clean otherwise (it's the purpose of the `linux-pkgs-valgrind` GitLab worker https://gitlab.com/petsc/petsc/-/blob/main/config/examples/arch-ci-linux-pkgs-valgrind.py in which there is no `--download-parmmg`).

Here is the log from ParMmg example. Again, MPICH is Valgrind-clean, so it's not coming from the MPI implementation itself.
```
==400003== 360 bytes in 1 blocks are definitely lost in loss record 7 of 9
==400003==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==400003==    by 0x4E1A737: MPL_malloc (mpl_trmem.h:280)
==400003==    by 0x4E1C9CE: MPIR_Csel_prune (csel.c:686)
==400003==    by 0x4E19C94: MPIR_Coll_comm_init (coll_impl.c:175)
==400003==    by 0x4E714FD: MPIR_Comm_commit (commutil.c:734)
==400003==    by 0x4E6C414: MPIR_init_comm_world (builtin_comms.c:33)
==400003==    by 0x4ECC13D: MPII_Init_thread (mpir_init.c:216)
==400003==    by 0x4ECBB22: MPIR_Init_impl (mpir_init.c:93)
==400003==    by 0x4CBF784: internal_Init (init.c:46)
==400003==    by 0x4CBF821: PMPI_Init (init.c:134)
==400003==    by 0x10A65E: main (main.c:43)
==400003==
==400003== 360 bytes in 1 blocks are definitely lost in loss record 8 of 9
==400003==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==400003==    by 0x4E1A737: MPL_malloc (mpl_trmem.h:280)
==400003==    by 0x4E1C9CE: MPIR_Csel_prune (csel.c:686)
==400003==    by 0x4E19C94: MPIR_Coll_comm_init (coll_impl.c:175)
==400003==    by 0x4E715A2: MPIR_Comm_commit (commutil.c:739)
==400003==    by 0x4E6C414: MPIR_init_comm_world (builtin_comms.c:33)
==400003==    by 0x4ECC13D: MPII_Init_thread (mpir_init.c:216)
==400003==    by 0x4ECBB22: MPIR_Init_impl (mpir_init.c:93)
==400003==    by 0x4CBF784: internal_Init (init.c:46)
==400003==    by 0x4CBF821: PMPI_Init (init.c:134)
==400003==    by 0x10A65E: main (main.c:43)
```

**Comment by prj-** [comment]
Just for good measure, in case you want to double-check this yourself, you could try this on your end:
1) comment this big chunk of code https://github.com/MmgTools/ParMmg/blob/develop/libexamples/adaptation_example1/main.c#L174-L571
2) run again

Here is what I get: no leaks are possible (at least with a proper MPI implementation, don't know about OpenMPI).
```
==401220== Command: ./main wave.mesh waveR.mesh 1
==401220== Parent PID: 401219
==401220==
==401220== Warning: set address range perms: large range [0xad70040, 0x1c018878) (defined)
==401220== Warning: set address range perms: large range [0xad70028, 0x1c018890) (noaccess)
==401220== Syscall param exit_group(status) contains uninitialised byte(s)
==401220==    at 0x538BED1: _Exit (_exit.c:30)
==401220==    by 0x52E75A1: __run_exit_handlers (exit.c:136)
==401220==    by 0x52E765F: exit (exit.c:143)
==401220==    by 0x52CBFD6: __libc_start_call_main (libc_start_call_main.h:74)
==401220==    by 0x52CC07C: __libc_start_main@@GLIBC_2.34 (libc-start.c:409)
==401220==    by 0x1092E4: (below main) (in /home/john/petsc/src/dm/impls/plex/tests/main)
==401220==  Uninitialised value was created by a stack allocation
==401220==    at 0x1093A9: main (main.c:33)
==401220==
==401220==
==401220== HEAP SUMMARY:
==401220==     in use at exit: 0 bytes in 0 blocks
==401220==   total heap usage: 5,334 allocs, 5,309 frees, 374,338,991 bytes allocated
==401220==
==401220== All heap blocks were freed -- no leaks are possible
==401220==
==401220== For lists of detected and suppressed errors, rerun with: -s
==401220== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
So I still believe there is something off in either `PMMG_parmmglib_distributed` or any other API functions being used in the commented chunk of code.

**Comment by Algiane** [comment]
Now the test runs without errors. Errors were inside ` MPI_Isend` calls when:
  - MPI_Request array was not properly allocated (wrong size);
  - MPI_Request array was not initialized to MPI_REQUEST_NULL;
  - MPI_Waitall call was missing.
  
The test works also if called with  `API_mode=0` (to Get/Set the parallel interfaces through triangles).

**Comment by prj-** [comment]
The devil is in the details... thanks a lot for your effort. I can now confirm that the PETSc example is not leaking anymore as well! 🎉
There is still a huge amount of warnings ([dump.150043.log](https://github.com/MmgTools/ParMmg/files/8053004/dump.150043.log)), but those are inside Mmg, and may be fixed by the upcoming `feature/anisomet` branch (you tell me), so I'll wait for this Mmg branch to be merged to bother you over there if the warnings do persist.

**Comment by Algiane** [comment]
Thanks for your feedback. Finding has been a nightmare (😂) but it allows to correct important errors.
I really hope that the feature/anisomet branch of Mmg will clean the other errors ;-).

**Comment by lcirrottola** [comment]
Thanks you both for your work!

**Pull request merged**
